#!/bin/sh
cd -- "$(dirname "$0")"
rm -f column_movie_Qeq.mp4
every=1
format="-c:v libx265 -tag:v hvc1"
width=1200
height=800
quality=18
while getopts e:w:h:q:l flag
do
    case "${flag}" in
        e) every=${OPTARG};;
        w) width=${OPTARG};;
        h) height=${OPTARG};;
        q) quality=${OPTARG};;
        l) format="-c:v libx264";;
    esac
done
gnuplot -c plot_column_Qeq $every $width $height | ffmpeg -f png_pipe -s:v "${width},${height}" -i pipe: $format -pix_fmt yuv420p -crf $quality -c:a aac column_movie_Qeq.mp4
